services:
  todo-api-postgres:
    image: postgres:17
    container_name: todo-api-postgres
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  todo-api:
    build: ./server
    container_name: todo-api
    ports:
      - "8000:8000" 
    environment:
      PGHOST: todo-api-postgres
      PGPORT: 5432
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
    depends_on:
      - todo-api-postgres

  nginx:
    image: nginx:1.27
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./server/nginx/log:/var/log/nginx
    depends_on:
      - todo-api

volumes:
  postgres-data:
